version: "3.0"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
     - zookeeper
    ports:
     - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  nifi:
    build: ./nifi
    image: apache/nifi:1.9.2
    ports:
     - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql:db
    volumes:
      - ./nifi/files/conf:/opt/nifi/nifi-current/conf/

  input_json:
    build: ./kafka
    depends_on:
     - kafka
    volumes:
      - ./kafka/files/input_json:/kafka/input_json/

  mysql:
    restart: always
    image: mysql/mysql-server:8.0.17
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql/init_scripts:/docker-entrypoint-initdb.d
      - ./mysql/data/mysql:/var/lib/mysql/
