version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
     - zookeeper
    ports:
     - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  nifi_json_to_sql:
    build: ./nifi/jsonToSQL
    ports:
     - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql:db

  nifi_data_aggregation:
    build: ./nifi/dataAggregation
    ports:
      - "8070:8070"
    environment:
      - NIFI_WEB_HTTP_PORT=8070
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8072
    links:
      - nifi_json_to_sql:nifi1
  
  web_input:
    build: ./kafka
    depends_on:
     - kafka
    ports:
     - "5000:5000"

  mysql:
    restart: always
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: mydb

  db_connection:
    build: ./mysql
    depends_on:
      - mysql
    links:
      - mysql:db